# Generated by Django 5.0.6 on 2024-06-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('precio_total', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='productos',
            field=models.ManyToManyField(to='web.producto'),
        ),
    ]
