# Generated by Django 5.0.6 on 2024-07-02 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_ordencompra_delete_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada'), ('rectificada', 'Rectificada')], default='creada', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='factura_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectificaciones', to='web.ordencompra'),
        ),
    ]
