# Generated by Django 5.0.6 on 2024-07-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_ordencompra_estado_ordencompra_factura_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='factura_original',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estado_entrega',
            field=models.CharField(choices=[('por_entregar', 'Por entregar'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada')], default='por_entregar', max_length=20),
        ),
    ]
