# Generated by Django 5.0.6 on 2024-07-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_ordencompra_factura_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada'), ('rectificada', 'Rectificada')], default='Creada', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado_entrega',
            field=models.CharField(choices=[('por_entregar', 'Por entregar'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada')], default='Porsdsds entregar', max_length=20),
        ),
    ]
