# Generated by Django 5.0.6 on 2024-07-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_ordencompra_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado_entrega',
            field=models.CharField(choices=[('por_entregar', 'Por entregar'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada')], default='Por entregar', max_length=20),
        ),
    ]
