# Generated by Django 5.0.6 on 2024-07-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_ordencompra_estado_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada'), ('rectificada', 'Rectificada')], default='creada', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado_entrega',
            field=models.CharField(choices=[('por_entregar', 'Por entregar'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada')], default='por_entregar', max_length=20),
        ),
    ]
