# Generated by Django 5.0.6 on 2024-07-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_ordencompra_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('CR', 'Creada'), ('RE', 'Rectificada')], default='CR', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado_entrega',
            field=models.CharField(choices=[('PE', 'Por entregar'), ('EN', 'Entregada'), ('RE', 'Rechazada')], default='PE', max_length=20),
        ),
    ]
