# Generated by Django 5.0.6 on 2024-07-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_ordencompra_direccion_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='imagen_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='rut_persona_recibe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
