# Generated by Django 5.0.6 on 2024-07-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_ordencompra_imagen_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('CR', 'Creada'), ('RE', 'Rectificada'), ('AN', 'Anulada')], default='CR', max_length=20),
        ),
    ]
